# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3db41aa5d1d3634fca58ff64b41c8bee73482d60aafb34a6d1ca3aca481aff13ec97774efc68b8959740bb74c7e285ec9bbbc156b4f1b2958b57f9b3749ce99

test:
  secret_key_base: bbc1b0977a22f6dfa891be504be6de3b7991aa47faa61a73075b4a839f309d65473438c74b7f2ceb4fab935e716eb9e026f6a1a91106cbcc17c81c77dc6be884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
